version: '3.5'

services:

    web-backend:
                 image: example-backend
                 ports:
                 - 8080:8080
                 environment:                        
                 - REDIS_HOST=redis_cache
                 - POSTGRES_HOST=postgres_db
                 - POSTGRES_PASSWORD=example
                 depends_on:
                 - postgres_db

    web-frontend:
                image: example-frontend
                ports:
                - 5000:5000

    redis_cache:
                image: redis
                ports:
                - 6379:6379
                restart: unless-stopped

    postgres_db:
            image: postgres:13.2-alpine
            restart: unless-stopped
            environment:
                   - POSTGRES_PASSWORD=example
            volumes:
                  - database:/var/lib/postgresql/data

volumes:
        database:
