FROM node:14-alpine

#ENV

#Change Work Dir
WORKDIR /app

#Expose port
EXPOSE 5000

# Upload project files
COPY . .

#RUN update and install packages
RUN npm install

#Build Nodejs
RUN REACT_APP_BACKEND_URL=http://localhost:8080 npm run build

#Serving Static file
#Install
RUN npm install -g serve

#Serve
CMD ["serve","-s","-l","5000","build"]

